import Vue from 'vue';
import {Button,Search,Swipe, SwipeItem,Popup,Cell} from 'vant';
import { Icon } from 'vant';
import { Tag } from 'vant';
import { List } from 'vant';
import { DropdownMenu, DropdownItem } from 'vant';
import { Empty } from 'vant';
import { Toast } from 'vant';
import { Tabbar, TabbarItem } from 'vant';
import { Col, Row } from 'vant';
import { Grid, GridItem } from 'vant';
import { Form } from 'vant';
import { Field } from 'vant';
import { GoodsAction, GoodsActionIcon, GoodsActionButton } from 'vant';
import { Sku } from 'vant';
import { Checkbox, CheckboxGroup } from 'vant';
import { Card } from 'vant';
import { SubmitBar } from 'vant';
import { Stepper } from 'vant';
import { SwipeCell } from 'vant';

Vue.use(SwipeCell);
Vue.use(Stepper);
Vue.use(SubmitBar);
Vue.use(Card);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Sku);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Form);
Vue.use(Field);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Col);
Vue.use(Row);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Toast);
Vue.use(Empty);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(List);
Vue.use(Tag);
Vue.use(Icon);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Search);
Vue.use(Button);
Vue.use(Popup);
Vue.use(Cell);